In [2]:
%load_ext autoreload
%autoreload 2

from kaggle_environments import make
from board_stack_plus import *
from parameters import *
import torch
import numpy as np

env = make("hungry_geese", debug=True)
env.reset(4)

Loading environment football failed: No module named 'gfootball'


[{'action': 'NORTH',
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60,
   'step': 0,
   'geese': [[38], [70], [37], [47]],
   'food': [18, 3],
   'index': 0},
  'status': 'ACTIVE'},
 {'action': 'NORTH',
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60, 'index': 1},
  'status': 'ACTIVE'},
 {'action': 'NORTH',
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60, 'index': 2},
  'status': 'ACTIVE'},
 {'action': 'NORTH',
  'reward': 0,
  'info': {},
  'observation': {'remainingOverageTime': 60, 'index': 3},
  'status': 'ACTIVE'}]

In [ ]:
np.set_printoptions(threshold=100000000)

In [ ]:
env.run(['agent/submission.py', 'agent/risk_averse_greedy.py', 'agent/boiler_goose.py', 'agent/risk_averse_greedy.py'])
env.render(mode="ipython", height=600, width=800)

print(encode_state_stack_plus(env.steps[20]))


In [10]:
env.reset(4)
print(env.done)
env.run(['submission.py', 'submission.py', 'agent/DenseNetAgent.py', 'agent/DenseNetAgent.py'])
print(env.done)
env.render(mode="ipython", height=600, width=800)

500
40
# for i in range(10):
#     print(env.steps[i][0], env.steps[i][0]["observation"]["geese"])


False
True


40

In [4]:
model = ConvDQN()

board_list, _, _, _ = encode_state(env.steps[0])

print(board_list[0].dtype)
t = torch.from_numpy(np.stack(board_list))
print(t.dtype)
t = t.unsqueeze(1).float()
print(t.dtype)
print(model.act(t, epsilon=0))
print(model.act(t, epsilon=0))

float64
torch.float64
torch.float32
tensor([0, 0, 0, 0])
tensor([0, 0, 0, 0])


In [12]:
env.render(mode="ipython", height=600, width=800)
print(encode_env_stack(env.state[0]["observation"]))


[[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  2.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  4.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  

In [32]:
env.step(["NORTH", "NORTH", "NORTH", "NORTH"])
print(env.state)
env.steps

InvalidArgument: 1 actions required.